[package]
name = "kloudstrap-rust"
version = "0.1.0"
authors = ["fred <fredlahde@gmail.com>"]
edition = "2018"

[dependencies]
zip = "0.5.2"
serde = "1.0.90"
serde_json = "1.0.39"
serde_derive = "1.0.90"
flate2 = "1.0.7"
tar = "0.4.22"
shiplift = "0.4"

